### ISSUE TITLE
baseOf.R -> gtools

### ISSUE THREAD

**Issue by smoe** [r-gregmisc/gplots#4]
https://github.com/r-gregmisc/gplots/blob/develop/R/baseOf.R was created as a helper function within venn. It should possibly find a more prominent position with gtools since this functionality to my knowledge is still unique in R.

**Comment by warnes** [comment]
@smoe I've created a repo for `gtools`, go ahead and submit a pull request to add `baseOf.R` there: https://github.com/r-gregmisc/gtools
